services:
  db:
    build:
      context: ./docker_mongo
      dockerfile: Dockerfile
    container_name: kryptos_db
    hostname: kryptos-db
    volumes:
      - /backup/kryptos/db:/data/db
    networks:
      - kryptos

  api:
    build:
      context: ./docker_kryptos
      dockerfile: Dockerfile
    container_name: kryptos_api
    hostname: kryptos-api
    depends_on:
      - db
    environment:
      - KRYPTOS_EMAIL_HOST_USER=user@my-mail.com
      - KRYPTOS_EMAIL_HOST_PASSWORD=abcdefghijklmnop
    dns:
      - 8.8.8.8
    networks:
      - kryptos

  bot:
    build:
      context: ./docker_kryptos_bot
      dockerfile: Dockerfile
    container_name: kryptos_bot
    hostname: kryptos-bot
    depends_on:
      - api
    environment:
      - KRYPTOS_BOT_API_TOKEN=THIS_IS_SECRET:THIS_IS_SECRET
    networks:
      - kryptos

networks:
  kryptos:
    driver: bridge
    ipam:
      config:
        - subnet: x.x.x.x/x   # Please Replace It!